[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
domin8_prgm = "9Did6kAH9Mkteyi4xCrrq5x8bjBPQ1o9zZEoGC2hSYnk"
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[programs.devnet]
domin8_prgm = "9Did6kAH9Mkteyi4xCrrq5x8bjBPQ1o9zZEoGC2hSYnk"
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/d/dev/royalrumble/seed/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
