[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
domin8_prgm = "8BH1JMeZCohtUKcfGGTqpYjpwxMowZBi6HrnAhc6eJFz"
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[programs.localnet]
domin8_prgm = "3HK2JxZBgv2zy8RnzLTYMCp55GV2xV7CyKqBhYFWV5Kq"
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/work/domin8/solana/7H9uSFKd1h4pvFPFfqzLpSZyLac7F9ax9ZcFtv9B5oDf.json"

[scripts]
test = "NODE_OPTIONS='--loader ts-node/esm' yarn mocha -t 1000000 tests/devnet.test.ts"
