[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
domin8_prgm = "EUG7PPKMmzssdsyCrR4XXRcN5xMp1eBLXgF1SAsp28hT"
domin8_mvp = "11111111111111111111111111111112"  # Will be updated after deploy
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[programs.localnet]
domin8_prgm = "EUG7PPKMmzssdsyCrR4XXRcN5xMp1eBLXgF1SAsp28hT"
domin8_mvp = "11111111111111111111111111111112"  # Will be updated after deploy
orao_vrf = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/work/domin8/solana/7H9uSFKd1h4pvFPFfqzLpSZyLac7F9ax9ZcFtv9B5oDf.json"

[scripts]
test = "NODE_OPTIONS='--loader ts-node/esm' yarn mocha -t 1000000 tests/devnet.test.ts"
test-comprehensive = "NODE_OPTIONS='--loader ts-node/esm' yarn mocha -t 1000000 tests/comprehensive.test.ts"
unlock-bets = "NODE_OPTIONS='--loader ts-node/esm' ts-node scripts/unlock-bets.ts"
set-counter = "NODE_OPTIONS='--loader ts-node/esm' ts-node scripts/set-counter.ts"
rotate-force = "NODE_OPTIONS='--loader ts-node/esm' ts-node scripts/rotate-force.ts"
