[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
domin8_vrf = "96ZRCG9KRB7Js6AENkVpTtwNUXqaxF8ZAAWrmxa8U2QF"

[programs.devnet]
domin8_vrf = "96ZRCG9KRB7Js6AENkVpTtwNUXqaxF8ZAAWrmxa8U2QF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
